[package]
name = "shadowdaughter/slvm"
description = "A Secure Lua Virtual Machine based on FiOne"
version = "1.0.0"
license = "GPL-3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["**"]
include = ["src", "default.project.json", "wally.toml", "LICENSE"]

[dependencies]