[package]
name = "hakai/SLVM"
description = "A Secure Lua Virtual Machine based on FiOne"
version = "1.0.0"
licene = "GPL-3.0-only"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["**"]
include = ["src", "default.project.json", "LICENSE"]

[dependencies]
